# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        AppBundle\Entity\Common\User: bcrypt

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        users:
            entity:
                class: AppBundle:Common\User
                property: username
        # in_memory:
            # memory: ~

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        login:
            pattern: /login$
            anonymous: ~
        secured_area:
            pattern: ^/
            form_login:
                login_path: admin_default_login
                check_path: admin_default_login_check
                default_target_path: /
            logout:
                path: admin_default_logout
                target: /
        # main:
            # anonymous: ~
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html

    role_hierarchy:
        ROLE_ADMIN: [ROLE_MASTER, ROLE_TRANSACTION, ROLE_REPORT]
        ROLE_TRANSACTION: [ROLE_SALE_DISCOUNT_APPLICATION, ROLE_SALE_ORDER, ROLE_PURCHASE_WORKSHOP_HEADER, ROLE_DELIVERY_WORKSHOP, ROLE_RECEIVE_WORKSHOP, ROLE_DELIVERY_ORDER, ROLE_PURCHASE_DELIVERY_ORDER, ROLE_RECEIVE_ORDER, ROLE_DELIVERY_INSPECTION_HEADER, ROLE_SALE_INVOICE, ROLE_SALE_PAYMENT, ROLE_PURCHASE_INVOICE_HEADER_UNIT, ROLE_PURCHASE_INVOICE_HEADER_WORKSHOP, ROLE_PURCHASE_INVOICE_HEADER_GENERAL, ROLE_PURCHASE_PAYMENT_HEADER, ROLE_PURCHASE_INVOICE_SPAREPART_HEADER]
        ROLE_SALE_DISCOUNT_APPLICATION: [ROLE_SALE_DISCOUNT_APPLICATION_NEW, ROLE_SALE_DISCOUNT_APPLICATION_EDIT, ROLE_SALE_DISCOUNT_APPLICATION_DELETE]
        ROLE_SALE_ORDER: [ROLE_SALE_ORDER_NEW, ROLE_SALE_ORDER_EDIT, ROLE_SALE_ORDER_DELETE]
        ROLE_PURCHASE_WORKSHOP_HEADER: [ROLE_PURCHASE_WORKSHOP_HEADER_NEW, ROLE_PURCHASE_WORKSHOP_HEADER_EDIT, ROLE_PURCHASE_WORKSHOP_HEADER_DELETE]
        ROLE_DELIVERY_WORKSHOP: [ROLE_DELIVERY_WORKSHOP_NEW, ROLE_DELIVERY_WORKSHOP_EDIT, ROLE_DELIVERY_WORKSHOP_DELETE]
        ROLE_RECEIVE_WORKSHOP: [ROLE_RECEIVE_WORKSHOP_NEW, ROLE_RECEIVE_WORKSHOP_EDIT, ROLE_RECEIVE_WORKSHOP_DELETE]
        ROLE_DELIVERY_ORDER: [ROLE_DELIVERY_ORDER_NEW, ROLE_DELIVERY_ORDER_EDIT, ROLE_DELIVERY_ORDER_DELETE]
        ROLE_PURCHASE_DELIVERY_ORDER: [ROLE_PURCHASE_DELIVERY_ORDER_NEW, ROLE_PURCHASE_DELIVERY_ORDER_EDIT, ROLE_PURCHASE_DELIVERY_ORDER_DELETE]
        ROLE_RECEIVE_ORDER: [ROLE_RECEIVE_ORDER_NEW, ROLE_RECEIVE_ORDER_EDIT, ROLE_RECEIVE_ORDER_DELETE]
        ROLE_DELIVERY_INSPECTION_HEADER: [ROLE_DELIVERY_INSPECTION_HEADER_NEW, ROLE_DELIVERY_INSPECTION_HEADER_EDIT, ROLE_DELIVERY_INSPECTION_HEADER_DELETE]
        ROLE_SALE_INVOICE: [ROLE_SALE_INVOICE_NEW, ROLE_SALE_INVOICE_EDIT, ROLE_SALE_INVOICE_DELETE]
        ROLE_SALE_PAYMENT: [ROLE_SALE_PAYMENT_NEW, ROLE_SALE_PAYMENT_EDIT, ROLE_SALE_PAYMENT_DELETE]
        ROLE_PURCHASE_INVOICE_HEADER_UNIT: [ROLE_PURCHASE_INVOICE_HEADER_UNIT_NEW, ROLE_PURCHASE_INVOICE_HEADER_UNIT_EDIT, ROLE_PURCHASE_INVOICE_HEADER_UNIT_DELETE]
        ROLE_PURCHASE_INVOICE_HEADER_WORKSHOP: [ROLE_PURCHASE_INVOICE_HEADER_WORKSHOP_NEW, ROLE_PURCHASE_INVOICE_HEADER_WORKSHOP_EDIT, ROLE_PURCHASE_INVOICE_HEADER_WORKSHOP_DELETE]
        ROLE_PURCHASE_INVOICE_HEADER_GENERAL: [ROLE_PURCHASE_INVOICE_HEADER_GENERAL_NEW, ROLE_PURCHASE_INVOICE_HEADER_GENERAL_EDIT, ROLE_PURCHASE_INVOICE_HEADER_GENERAL_DELETE]
        ROLE_PURCHASE_PAYMENT_HEADER: [ROLE_PURCHASE_PAYMENT_HEADER_NEW, ROLE_PURCHASE_PAYMENT_HEADER_EDIT, ROLE_PURCHASE_PAYMENT_HEADER_DELETE]
