# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.transaction.sale_discount_application_repository:
        class: AppBundle\Repository\Transaction\SaleDiscountApplicationRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - AppBundle\Entity\Transaction\SaleDiscountApplication

    app.transaction.sale_discount_application_form:
        class: AppBundle\Service\Transaction\SaleDiscountApplicationForm
        arguments: ["@app.transaction.sale_discount_application_repository"]

    app.transaction.sale_order_repository:
        class: AppBundle\Repository\Transaction\SaleOrderRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - AppBundle\Entity\Transaction\SaleOrder

    app.transaction.sale_order_form:
        class: AppBundle\Service\Transaction\SaleOrderForm
        arguments: ["@app.transaction.sale_order_repository"]

    app.transaction.delivery_inspection_header_repository:
        class: AppBundle\Repository\Transaction\DeliveryInspectionHeaderRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - AppBundle\Entity\Transaction\DeliveryInspectionHeader

    app.transaction.delivery_inspection_header_form:
        class: AppBundle\Service\Transaction\DeliveryInspectionHeaderForm
        arguments: ["@app.transaction.delivery_inspection_header_repository"]

    app.transaction.receive_order_repository:
        class: AppBundle\Repository\Transaction\ReceiveOrderRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - AppBundle\Entity\Transaction\ReceiveOrder

    app.transaction.receive_order_form:
        class: AppBundle\Service\Transaction\ReceiveOrderForm
        arguments: ["@app.transaction.receive_order_repository"]

    app.transaction.delivery_workshop_repository:
        class: AppBundle\Repository\Transaction\DeliveryWorkshopRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - AppBundle\Entity\Transaction\DeliveryWorkshop

    app.transaction.delivery_workshop_form:
        class: AppBundle\Service\Transaction\DeliveryWorkshopForm
        arguments: ["@app.transaction.delivery_workshop_repository"]

    app.transaction.delivery_order_repository:
        class: AppBundle\Repository\Transaction\DeliveryOrderRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - AppBundle\Entity\Transaction\DeliveryOrder

    app.transaction.delivery_order_form:
        class: AppBundle\Service\Transaction\DeliveryOrderForm
        arguments: ["@app.transaction.delivery_order_repository"]

    app.transaction.purchase_workshop_header_repository:
        class: AppBundle\Repository\Transaction\PurchaseWorkshopHeaderRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - AppBundle\Entity\Transaction\PurchaseWorkshopHeader

    app.transaction.purchase_workshop_header_form:
        class: AppBundle\Service\Transaction\PurchaseWorkshopHeaderForm
        arguments: ["@app.transaction.purchase_workshop_header_repository"]

    app.transaction.receive_workshop_repository:
        class: AppBundle\Repository\Transaction\ReceiveWorkshopRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - AppBundle\Entity\Transaction\ReceiveWorkshop

    app.transaction.receive_workshop_form:
        class: AppBundle\Service\Transaction\ReceiveWorkshopForm
        arguments: ["@app.transaction.receive_workshop_repository"]

    app.transaction.sale_invoice_repository:
        class: AppBundle\Repository\Transaction\SaleInvoiceRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - AppBundle\Entity\Transaction\SaleInvoice

    app.transaction.sale_invoice_form:
        class: AppBundle\Service\Transaction\SaleInvoiceForm
        arguments: ["@app.transaction.sale_invoice_repository"]

    app.transaction.sale_payment_repository:
        class: AppBundle\Repository\Transaction\SalePaymentRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - AppBundle\Entity\Transaction\SalePayment

    app.transaction.sale_payment_form:
        class: AppBundle\Service\Transaction\SalePaymentForm
        arguments: ["@app.transaction.sale_payment_repository"]

    app.transaction.purchase_invoice_header_repository:
        class: AppBundle\Repository\Transaction\PurchaseInvoiceHeaderRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - AppBundle\Entity\Transaction\PurchaseInvoiceHeader

    app.transaction.purchase_invoice_header_form:
        class: AppBundle\Service\Transaction\PurchaseInvoiceHeaderForm
        arguments: ["@app.transaction.purchase_invoice_header_repository"]

    app.transaction.purchase_payment_header_repository:
        class: AppBundle\Repository\Transaction\PurchasePaymentHeaderRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - AppBundle\Entity\Transaction\PurchasePaymentHeader

    app.transaction.purchase_payment_header_form:
        class: AppBundle\Service\Transaction\PurchasePaymentHeaderForm
        arguments: ["@app.transaction.purchase_payment_header_repository"]

    app.transaction.purchase_delivery_order_repository:
        class: AppBundle\Repository\Transaction\PurchaseDeliveryOrderRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - AppBundle\Entity\Transaction\PurchaseDeliveryOrder

    app.transaction.purchase_delivery_order_form:
        class: AppBundle\Service\Transaction\PurchaseDeliveryOrderForm
        arguments: ["@app.transaction.purchase_delivery_order_repository"]

    app.transaction.purchase_invoice_sparepart_header_repository:
        class: LibBundle\Doctrine\EntityRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - AppBundle\Entity\Transaction\PurchaseInvoiceSparepartHeader

    app.transaction.purchase_invoice_sparepart_header_sheet:
        class: AppBundle\Service\Transaction\PurchaseInvoiceSparepartHeaderSheet
        arguments: ["@validator",  "@lib.excel.object_parser", "@app.transaction.purchase_invoice_sparepart_header_repository"]
